### PR TITLE
refactor(qt): simplify GUIUtill[fonts] API

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
There's overcomplicated public header `guiutil_fonts.h` which introduces bunch of static methods inside global variables, such as g_fonts_known, g_font_registry

guiutil.h has internal classes `FontInfo` and `FontRegistry` in public namespace.

class `FontAttrib` is also non-needed abstraction.

## What was done?
This PR simplifies public API for GUIUtil [fonts].

Particularly, done:
 - several new static methods are introduced in public API GUIUtil [font] such as: `setWeightFromArg`, `currentWeightArg`, `defaultWeightArg`, `supportedWeightArgs` for UI settings
 - classes `FontInfo`, `FontRegistry` and global objects `g_fonts_known`, `g_font_registry` are removed from public API GUIUtil [font]
 - removed `weightFromArg`, `weightToArg`, `WeightToIdx` and `IdxToWeight` helpers from public API GUIUtil [font]
 - simplified methods `getFonts`, `registerFont` and `setActiveFont` to just `setActiveFont()`
 - merged `isValidWeightArg` and `setWeightFromArg` to `bool setWeightFromArg()`
 - move FontAttrib to cpp file as a part of private implementation
 - drop multiple unused headers and forward declarations from guiutil_font.h, such as QFont, QWidget, QTextEdit, font names [MONTSERRAT_FONT_STR, OS_FONT_STR, OS_MONO_FONT_STR, ROBOTO_MONO_FONT_STR]
 - drop `LoadFont` helper that is super-seeded by multiple rich dash core helpers
 - after simplification of API, the header `qt/guiutil_font.h` is inlined to to `guiutil.h`
 - replaced BitcoinGUI::DEFAULT_UIPLATFORM to GUIUtil::defaultUIPlatform. It helps to break circular dependency over qt/guiutil by introducing slight extra diversity with Bitcoin Core. It doesn't block further backporting because this part of code rarely touch in Bitcoin Core and it will cause compilation error if any logical conflict, it's safe to change

Unrelated extra changes:
 - renamed `registerWidget` to `setStyledHtml` which is more clear for develop.

As a result of this PR multiple usages of GUIUtil[font] became much simplier, for example:

```diff
-if (auto font_name = QString::fromStdString(SettingToString(node().getPersistentSetting("font-family"), GUIUtil::defaultFontFamily().toStdString()));
-    GUIUtil::registerFont(font_name, /*selectable=*/true) && GUIUtil::setActiveFont(font_name)) {
-    GUIUtil::setApplicationFont();
-}
+const QString font_name = QString::fromStdString(
+    SettingToString(node().getPersistentSetting("font-family"), ""));
+GUIUtil::setActiveFont(font_name);
```

## How Has This Been Tested?
Run `dash-qt` and played with all sliders and combo-boxes on Appearance Tab. Seems as nothing is broken.

Two circular dependencies are gone:

    -    "qt/appearancewidget -> qt/guiutil -> qt/appearancewidget",
    -    "qt/bitcoingui -> qt/guiutil -> qt/bitcoingui",

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by thepastaclaw — CHANGES_REQUESTED** [review]
## Code Review

Verified against HEAD 98ac82eb4125e28c909b6ee29a17e675289322ce and the requested diff. Both reported issues are introduced by this PR: the weight sliders now expose raw weight-arg ranges instead of dense supported-weight indices, which can leave the slider and registry out of sync for sparse supported sets, and `fixedPitchFont()` was changed from `getFont({... , FontWeight::Normal})` to constructing a plain `QFont`, so monospace callers no longer inherit the configured normal weight.

🔴 1 blocking | 🟡 1 suggestion(s)

_Reviewed queued commit `98ac82eb`. The PR head has since advanced to `95a3867a`; a follow-up queue item exists for the newer commit._

_Inline comment posting failed; posting findings in the review body instead._

### Blocking: Weight sliders can now select unsupported font weights and leave UI/model out of sync

`src/qt/appearancewidget.cpp:245`

This PR changes the sliders from dense indices over `GetSupportedWeights()` to raw weight args. `updateWeightSlider()` now sets the range to `supported.front()..supported.back()`, while `updateFontWeightNormal()` / `updateFontWeightBold()` pass the slider value directly to `setWeightFromArg()`. `supportedWeightArgs()` is built from the active font's supported subset, and `CalcSupportedWeights()` can produce sparse sets, so intermediate slider positions are possible. For those positions `setWeightFromArg()` returns false and leaves the registry unchanged, but the return value is ignored, so the slider can move to a value the model did not accept.

### Suggestion: fixedPitchFont() no longer respects the configured normal font weight

`src/qt/guiutil.cpp:241`

Before this PR, `fixedPitchFont()` returned `getFont({use_embedded_font ? ROBOTO_MONO_FONT_STR : OS_MONO_FONT_STR, FontWeight::Normal})`, which resolved through the font registry and therefore used the configured normal-weight selection. This PR replaces that with a plain `QFont` that only sets family/style-hint, so monospace callers such as `OptionsModel::getFontForChoice()`, `ProposalModel`, and `RPCConsole` stop tracking the user's configured normal weight.

**Review by thepastaclaw — CHANGES_REQUESTED** [review]
## Code Review

Latest delta (`98ac82eb..95a3867a`) only updates the stylesheet default platform lookup and removes dead includes; I found no new latest-delta findings. Cumulatively, both prior Qt font findings are STILL VALID at `95a3867a`: the unsupported weight-slider issue remains blocking, and `fixedPitchFont()` still bypasses the configured normal weight.

🔴 1 blocking | 🟡 1 suggestion(s)

### Findings

<details open>
<summary><b>🔴 Blocking:</b> Weight sliders still allow unsupported values and can persist a font weight the active font never accepted</summary>

`src/qt/appearancewidget.cpp`:245-299

Prior review finding revalidated: STILL VALID. `updateWeightSlider()` sets each slider to the numeric range between `supported.front()` and `supported.back()`, but `supportedWeightArgs()` is built from `FontInfo::CalcSupportedWeights()`, which can return a sparse subset of the `0..8` weight args. That lets the sliders stop on values that are inside the range but not actually supported by the active font. When that happens, `updateFontWeightNormal()` and `updateFontWeightBold()` pass the raw slider value into `GUIUtil::setWeightFromArg()`, which rejects unsupported weights and leaves the registry unchanged, but the return value is ignored. Because the sliders are mapped directly to `OptionsModel::FontWeightNormal` and `OptionsModel::FontWeightBold` and submitted on accept, the UI can save an unsupported weight arg even though the live font state never switched to it.

</details>

<details open>
<summary><b>🟡 Suggestion:</b> fixedPitchFont() no longer follows the configured normal-weight selection</summary>

`src/qt/guiutil.cpp`:241-247

Prior review finding revalidated: STILL VALID. Before this refactor, `fixedPitchFont()` returned a registry-backed font via `getFont(...)`, so the monospace helper inherited the current normal-weight selection. The current implementation constructs a fresh `QFont` from either `"Roboto Mono"` or `QFontDatabase::systemFont(QFontDatabase::FixedFont)` and only sets the monospace style hint, so the selected normal weight is dropped. That difference is observable at current HEAD in direct consumers such as `ProposalModel::data()` and `RPCConsole::clear()`, which use the returned `QFont` as-is instead of overriding its weight afterward.

</details>

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
please handle automated reviews

**Comment by thepastaclaw** [comment]
✅ Review complete (commit d4badd11)

**Review by thepastaclaw — APPROVED** [review]
## Code Review

Qt GUI font-API refactor that hides FontRegistry/FontInfo/FontAttrib behind free functions, inlines guiutil_font.h into guiutil.h, and replaces BitcoinGUI::DEFAULT_UIPLATFORM with GUIUtil::defaultUIPlatform. Both independent agents converge on no in-scope findings, and prior regressions (weight snapping in appearancewidget, fixedPitchFont routing) are resolved at HEAD.

File: src/qt/guiutil_font.cpp [hunk 1]
```diff
@@ -28,6 +29,119 @@
...
+    ~FontInfo();
+
+private:
+    QFont::Weight GetBestMatch(const QString& font_name, QFont::Weight target);
+    void CalcDefaultWeights(const QString& font_name);
+    void CalcSupportedWeights(const QString& font_name);
+};
+
+//! Global font state (active family, scale, per-font cache). File-private —
+//! external callers go through the free-function API in qt/guiutil_font.h.
```
Comment (UdjinM6) [inline src/qt/guiutil_font.cpp]: nit:
```suggestion
//! external callers go through the free-function API in qt/guiutil.h.
```

**Review by UdjinM6 — DISMISSED** [review]
utACK 77beedd49d8002b4155b00e7c16c1fa87e8b3332

**Review by UdjinM6 — APPROVED** [review]
utACK d4badd119a3ff7bed70caf4762516d87d2f0d395

**Review by thepastaclaw — APPROVED** [review]
## Code Review

Cumulative review of PR #7336 at d4badd119a. The latest delta (77beedd..d4badd11) is a one-line comment fix updating a header reference in guiutil_font.cpp following the prior header-inlining commit. The cumulative refactor encapsulates the Qt font registry behind a free-function GUIUtil API, removes two real circular dependencies (qt/appearancewidget and qt/bitcoingui via qt/guiutil), and relocates DEFAULT_UIPLATFORM. No prior findings were carried forward (prior review had none). Codex and CodeRabbit reported no findings. Claude's three nitpicks all describe either pre-existing behavior preserved by the refactor or purely speculative future-proofing; none are concrete bugs.
