### PR TITLE
fix: avoid maybe-uninitialized warning in ScopedBLSLegacyScheme

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented

`develop` is currently red: the `linux64_nowallet` build fails with

```
validation.cpp:167:34: error: 'enter' may be used uninitialized [-Werror=maybe-uninitialized]
```

GCC 14 at `-O2` (the nowallet job's compiler) loses track of the `has_value()` check guarding the `std::optional<bool>` payload read in `ScopedBLSLegacyScheme`'s constructor when the guard is default-constructed from `ConnectTip`. Introduced by 311efbc18149; every PR based on the current tip inherits the failure.

## What was done?

Replaced the `std::optional<bool>` constructor parameter with a default constructor and an explicit `bool` constructor. Both existing value-passing call sites already pass a plain `bool` (`!DeploymentActiveAt(...)`), so no caller changes; the optional deref the warning pointed at no longer exists. No behavior change.

The asan `test_dash-qt` QThread leak that was briefly bundled here has been split into its own PR per review feedback, so this PR is only the build fix.

## How Has This Been Tested?

- Local build (clang, macOS) clean; `test_dash --run_test=evo_dip3_activation_tests` and `bls_tests` pass.
- The failing configuration is GCC 14 `-Werror` in the `linux64_nowallet` CI job — this PR's CI run is the authoritative check.

## Breaking Changes

None.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by thepastaclaw** [comment]
✅ Final review complete — no blockers (commit 0d092f58)

File: src/validation.cpp [hunk 1]
```diff
@@ -153,20 +153,24 @@ namespace {
 //! boundary; this keeps a failed or dry-run validation from leaking that
 //! change into the process-wide flag.
 //!
-//! `enter` establishes the scheme for the scope. The flag is process-wide but
-//! the correct value is per-chainstate, so a background chainstate validating
-//! pre-V19 blocks under an active post-V19 snapshot must set it on entry
-//! (ProcessSpecialTxsInBlock only ever switches legacy->basic) and must not
-//! commit it back to the active chainstate's consumers.
+//! The `enter` constructor establishes the scheme for the scope. The flag is
```
Comment (knst) [inline src/validation.cpp]: nit: Comment should not be changed, because behaviour is not changed. Revert it please

File: test/sanitizer_suppressions/lsan [hunk 2]
```diff
@@ -3,3 +3,7 @@ leak:libQt5Widgets
 leak:QDBusConnectionPrivate
 leak:QDBusConnectionManager
 leak:QLayoutPrivate
+# QDBusConnectionManager lazily spawns a watcher QThread that is never joined
+# before process exit; the manager itself is suppressed above but the thread
+# object's allocation carries only the QThread constructor frame.
+leak:QThread::QThread
```
Comment (thepastaclaw) [inline test/sanitizer_suppressions/lsan]: **🟡 Suggestion: Avoid suppressing leaks from every QThread constructor**

LeakSanitizer suppression templates match any allocation stack containing the named symbol. Because both CI configurations load this suppression file through the common `LSAN_OPTIONS`, `leak:QThread::QThread` is not limited to the QDBus watcher: it also suppresses constructor-owned allocations for application QThreads created by `ClientModel`, `ClientFeeds`, `Intro`, `WalletController`, and other Qt paths. This can hide leaks whose only identifying allocation frame is the generic constructor, just as described for the current 120-byte leak. Restrict the rule to the affected test or process, obtain a QDBus-specific frame with better unwinding, or fix the watcher lifecycle instead of applying this generic symbol suppression throughout sanitizer testing.

<sub>source: ['codex']</sub>

**Review by thepastaclaw — COMMENTED** [review]
## Final validation — Codex/Sol only (Phase 2 disabled)

The `ScopedBLSLegacyScheme` constructor split preserves the behavior of all four call sites while removing the optional dereference implicated in the GCC warning. The LSan addition addresses the reported Qt failure, but its generic `QThread` match weakens leak detection across sanitizer processes and should be scoped more narrowly.
Source: reviewer backend model: gpt-5.6-sol; final verifier backend model: gpt-5.6-sol; orchestration only (not reviewer evidence): openclaw-agent/cliproxy/gpt-5.6-sol.

Validated zero-blocker Codex/Sol precheck evidence was promoted to final because Phase 2 (Sonnet/Opus) is temporarily disabled. This is Codex/Sol-only final validation, not Codex + Sonnet/Opus coverage.

### Review provenance
- Codex reviewers: `gpt-5.6-sol` — general (completed)
- Verifier: `gpt-5.6-sol` — verifier
- Sonnet/Opus: **not run (Phase 2 disabled — temporary Codex/Sol-only final)**
- Secondary pass: disabled (`temporary_phase2_sonnet_disable`)

🟡 1 suggestion(s)

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
These findings are from an automated code review. Verify each finding against the current code and only fix it if needed.

In `test/sanitizer_suppressions/lsan`:
- [SUGGESTION] test/sanitizer_suppressions/lsan:9: Avoid suppressing leaks from every QThread constructor
  LeakSanitizer suppression templates match any allocation stack containing the named symbol. Because both CI configurations load this suppression file through the common `LSAN_OPTIONS`, `leak:QThread::QThread` is not limited to the QDBus watcher: it also suppresses constructor-owned allocations for application QThreads created by `ClientModel`, `ClientFeeds`, `Intro`, `WalletController`, and other Qt paths. This can hide leaks whose only identifying allocation frame is the generic constructor, just as described for the current 120-byte leak. Restrict the rule to the affected test or process, obtain a QDBus-specific frame with better unwinding, or fix the watcher lifecycle instead of applying this generic symbol suppression throughout sanitizer testing.
```
</details>

File: src/validation.cpp [hunk 3]
```diff
@@ -153,20 +153,24 @@ namespace {
...
 public:
-    explicit ScopedBLSLegacyScheme(std::optional<bool> enter = std::nullopt) noexcept :
+    ScopedBLSLegacyScheme() noexcept :
         m_saved(bls::bls_legacy_scheme.load())
     {
-        if (enter.has_value() && *enter != m_saved) {
-            bls::bls_legacy_scheme.store(*enter);
-            LogPrintf("ScopedBLSLegacyScheme: entered bls_legacy_scheme=%d\n", *enter);
+    }
+    explicit ScopedBLSLegacyScheme(bool enter) noexcept :
```
Comment (knst) [inline src/validation.cpp:168]: NOTE FOR REVIEWERS:
that is silly fix but it is required because false-alarm in gcc

See relevant changes in mainstream Bitcoin Core:

```
commit 5294f0d5a94cc7beaf692131fba0cad8beec9f13
Author: fanquake <fanquake@gmail.com>
Date:   Mon Mar 22 11:22:06 2021 +0800

    refactor: return std::nullopt instead of {}

    In #21415 we decided to return `std::optional` rather than `{}` for
    uninitialized values. This PR repalces the two remaining usages of `{}`
    with `std::nullopt`.

    As a side-effect, this also quells the spurious GCC 10.2.x warning that
    we've had reported quite a few times. i.e #21318, #21248, #20797.

    ```bash
    txmempool.cpp: In member function 'CTxMemPool::setEntries CTxMemPool::GetIterSet(const std::set<uint256>&) const':
    txmempool.cpp:898:13: warning: '<anonymous>' may be used uninitialized in this function [-Wmaybe-uninitialized]
      898 |     return {};
          |             ^
```

It's false alarm in gcc, so, std::optional should not be default initialized to avoid warnings.

File: test/sanitizer_suppressions/lsan [hunk 4]
```diff
@@ -3,3 +3,7 @@ leak:libQt5Widgets
 leak:QDBusConnectionPrivate
 leak:QDBusConnectionManager
 leak:QLayoutPrivate
+# QDBusConnectionManager lazily spawns a watcher QThread that is never joined
+# before process exit; the manager itself is suppressed above but the thread
+# object's allocation carries only the QThread constructor frame.
```
Comment (knst) [inline test/sanitizer_suppressions/lsan]: IMO explanation in PR body is enough. 

@thepastaclaw please figure out why exactly Dash Core does need this exception but Bitcoin Core never had it?

**Review by knst — COMMENTED** [review]
Changes in ScopedBLSLEgacyScheme looks legit.

For QThread I want pasta-claw's response first.

File: test/sanitizer_suppressions/lsan (hunk 4 above)
Comment (knst) [reply test/sanitizer_suppressions/lsan]: do https://github.com/bitcoin/bitcoin/pull/35937 instead of QThread - seems as leaks are forever-friends for Qt Apps

File: src/validation.cpp (hunk 1 above)
Comment (PastaPastaPasta) [reply src/validation.cpp]: Done in 0d092f5813f1 — comment wording restored verbatim; only the constructor split remains. The LSan/QThread suppression has also been dropped from this PR entirely and moved to a separate PR so this one is just the build fix.

---
🤖 Posted autonomously by Claude on behalf of pasta.

**Comment by PastaPastaPasta** [comment]
most builds look happy here: https://github.com/PastaPastaPasta/dash/actions/runs/31641899026/job/94266577757

**Review by thepastaclaw — APPROVED** [review]
## Final validation — Codex/Sol only (Phase 2 disabled)

The constructor split preserves the behavior of all four ScopedBLSLegacyScheme call sites while removing the optional payload access that triggered GCC's maybe-uninitialized warning. The prior generic QThread LeakSanitizer suppression was removed from the current PR, and no in-scope defects remain.
Source: reviewer backend model: gpt-5.6-sol; final verifier backend model: gpt-5.6-sol; orchestration-only (not reviewer evidence): openclaw-agent/cliproxy/gpt-5.6-sol.

Validated zero-blocker Codex/Sol precheck evidence was promoted to final because Phase 2 (Sonnet/Opus) is temporarily disabled. This is Codex/Sol-only final validation, not Codex + Sonnet/Opus coverage.

### Review provenance
- Codex reviewers: `gpt-5.6-sol` — general (completed)
- Verifier: `gpt-5.6-sol` — verifier
- Sonnet/Opus: **not run (Phase 2 disabled — temporary Codex/Sol-only final)**
- Secondary pass: disabled (`temporary_phase2_sonnet_disable`)

File: test/sanitizer_suppressions/lsan (hunk 2 above)
Comment (thepastaclaw) [reply test/sanitizer_suppressions/lsan]: Resolved in this update — _Avoid suppressing leaks from every QThread constructor_ no longer present.

<sub>Auto-resolved by the review system based on the latest commit diff. If you believe this was closed in error, reopen the thread.</sub>
